#' Calibrate survey weights using ReGenesees
#'
#' Creates a calibrated survey design using the ReGenesees package and
#' applies calibration weighting to align survey estimates with known
#' population totals.
#'
#' The function:
#' \itemize{
#'   \item Converts character variables in the survey data to factors.
#'   \item Creates a population template based on the calibration model.
#'   \item Merges the supplied population totals with the template.
#'   \item Constructs a survey design object.
#'   \item Performs calibration using the specified calibration function.
#'   \item Returns the calibrated dataset and associated calibration
#'   population objects.
#' }
#'
#' This function acts as a wrapper around the ReGenesees functions
#' `pop.template()`, `e.svydesign()` and `e.calibrate()`.
#'
#' @param rf.data A data frame containing survey records to be calibrated.
#'
#' @param df.population A data frame containing calibration totals. Must
#'   contain variables named `name` and `total`, where `name` corresponds
#'   to calibration categories generated by `pop.template()`.
#'
#' @param ids A survey design formula specifying the survey unit identifier.
#'   Defaults to `~Serial_N`.
#'
#' @param strata A survey design formula specifying survey strata. Defaults
#'   to `NULL` for unstratified calibration.
#'
#' @param model A calibration model formula describing the variables used
#'   in calibration. Defaults to `~LA:sext:ageband - 1`.
#'
#' @param preweight Character string containing the name of the weight
#'   variable to be used as the input weight before calibration.
#'
#' @param calfun Character string specifying the calibration method.
#'   Defaults to `"raking"`.
#'
#' @param bounds Numeric vector of length two specifying lower and upper
#'   calibration bounds.
#'
#' @param aggregate.stage Optional aggregation stage argument passed to
#'   `e.calibrate()`.
#'
#' @param sigma2 Optional variance parameter passed to `e.calibrate()`.
#'
#' @returns A list containing:
#' \itemize{
#'   \item `data` - The calibrated survey dataset including calibrated
#'   weights.
#'   \item `poptemp` - The population template generated from the survey
#'   data and calibration model.
#'   \item `poptot` - The population totals matrix used in calibration.
#' }
#'
#' @examples
#' \dontrun{
#' result <- calibrate_weights(
#'   rf.data = household,
#'   df.population = totals,
#'   ids = ~Serial_N,
#'   model = ~y22 + y23 + y24 + y25 + hh2 + agesex - 1,
#'   preweight = "preweight1",
#'   calfun = "raking"
#' )
#'
#' calibrated_data <- result$data
#' }

calibrate_weights <- function(
    rf.data,
    df.population,
    ids = ~Serial_N,
    strata = NULL,
    model = ~LA:sext:ageband - 1,
    preweight = "preweight1",
    calfun = "raking",
    bounds = c(0.1, 10000),
    aggregate.stage = NULL,
    sigma2 = NULL
) {
  
  # Convert character variables to factors ----
  
  rf.data <- rf.data %>%
    mutate(across(where(is.character), as.factor))
  
  # Create population template ----
  
  pop <- pop.template(rf.data, calmodel = model)
  
  # Standardise names ----
  
  df.population$name <- sub("^la", "LA", df.population$name)
  
  # Convert template for merge ----
  
  pop2 <- t(pop)
  
  colnames(pop2) <- "NA"
  
  pop.names <- data.frame(name = rownames(pop2))
  

  # Merge calibration totals ----

  merge1 <- merge(pop.names, df.population, by = "name",
                  all.x = TRUE, sort = FALSE)
  
  # Replace missing controls with zero
  
  merge1[!complete.cases(merge1), "total"] <- 0
  
  merge2 <- data.frame(merge1[, "total"])
  
  rownames(merge2) <- merge1[, "name"]
  
  merge3 <- t(merge2)
  
  final_pop <- data.frame(merge3)
  
  colnames(final_pop) <- colnames(merge3)
  
  # Create survey design ----
  
  design <- e.svydesign(
      data = as.data.frame(rf.data),
      ids = ids,
      strata = strata,
      weights = as.formula(paste0("~", preweight))
      )
  
  # Calibration ----
  
  calibrated <- e.calibrate(
      design = design,
      df.population = final_pop,
      calmodel = model,
      calfun = calfun,
      bounds = bounds,
      aggregate.stage = aggregate.stage,
      sigma2 = sigma2
    )
  
  # Extract calibrated data ----
  
  calibrated_data <- calibrated$variables
  
  # Return outputs ----
  
  list(
    data = calibrated_data,
    poptemp = pop,
    poptot = final_pop
  )
  
}
